[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bestoffer = "ET53DG44KdWyNb96hShnJwxurr6x2cij9GRhacVhGQYt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://turbine-solanad-4cde.devnet.rpcpool.com/168dd64f-ce5e-4e19-a836-f6482ad6b396"
#cluster = "localnet"
wallet = "./turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha --parallel false -p ./tsconfig.json -t 1000000 tests/bestoffer.ts"