sequenceDiagram
    actor Buyer as Buyer
    participant Main as BestOffer Progam
    participant BuyingIntent as Buying Intent Account (PDA)<br/>
    participant Offer as Offer Account (PDA)
    participant Vault as Offer Vault Account (PDA)
    actor Seller as Seller
    Main -->> Buyer: Notify tracking information
    Note left of Main: Notification system <br/>is still to determined